const catchAsync = require('../utils/catchAsync');
const Alert = require('../models/Alert');

exports.getAlerts = catchAsync(async (req, res) => {
  const alerts = await Alert.find().sort({ createdAt: -1 }).limit(100);

  res.status(200).json({
    success: true,
    count: alerts.length,
    data: alerts
  });
});

exports.getAlertById = catchAsync(async (req, res) => {
  res.status(200).json({
    status: 'success',
    data: { alert: { id: req.params.id, message: 'Mock Alert' } }
  });
});

exports.createAlert = catchAsync(async (req, res) => {
  const alert = await Alert.create(req.body);

  res.status(201).json({
    success: true,
    data: alert
  });
});

exports.updateAlert = catchAsync(async (req, res) => {
  res.status(200).json({
    status: 'success',
    data: { alert: { ...req.body, id: req.params.id } }
  });
});

exports.deleteAlert = catchAsync(async (req, res) => {
  res.status(204).json({
    status: 'success',
    data: null
  });
});

exports.markAlertAsRead = catchAsync(async (req, res) => {
  res.status(200).json({
    status: 'success',
    data: { message: 'Marked as read' }
  });
});

exports.getUserAlerts = catchAsync(async (req, res) => {
  // Fetch all alerts from database, newest first
  const alerts = await Alert.find().sort({ createdAt: -1 }).limit(50);
  
  res.status(200).json({
    success: true,
    data: alerts
  });
});

exports.triggerEmergencyAlert = catchAsync(async (req, res) => {
  console.log('🚨 ALERT TRIGGER RECEIVED on Backend');
  const { exec } = require('child_process');
  const path = require('path');
  
  const scriptPath = path.join(__dirname, '../Alert/alerts.py');
  const scriptDir = path.dirname(scriptPath);
  
  console.log(`Executing alert script in: ${scriptDir}`);

  // Execute from the script directory so imports work
  exec(`python alerts.py`, { cwd: scriptDir }, async (error, stdout, stderr) => {
    if (error) {
      console.error(`exec error: ${error}`);
      return res.status(500).json({ status: 'error', message: 'Failed to execute alert script', error: error.message });
    }
    
    console.log(`stdout: ${stdout}`);
    if (stderr) console.error(`stderr: ${stderr}`);

    // MISSION: Store this manual alert in the database
    try {
      let pyResult = {};
      try {
        pyResult = JSON.parse(stdout);
      } catch (e) {
        // Fallback if stdout isn't clean JSON
        const match = stdout.match(/\{"status".*\}/);
        if (match) pyResult = JSON.parse(match[0]);
      }

      const risk = pyResult.risk || 'emergency';
      const count = pyResult.details ? pyResult.details.length : 0;
      
      // Create Alert document
      await Alert.create({
        title: `Manual Emergency Broadcast: ${risk.toUpperCase()}`,
        message: `A manual emergency alert for ${risk} has been successfully dispatched to ${count} recipients via Twilio and Mesh network.`,
        type: risk === 'heatwave' || risk === 'flood' || risk === 'drought' ? 'weather' : 'emergency',
        priority: 'high',
        severity: 'critical',
        status: 'active',
        trigger: {
          source: 'manual',
          autoGenerated: false
        },
        metadata: {
          createdBy: req.user?._id,
          source: 'Dashboard Manual Trigger'
        }
      });
      console.log('✅ Manual alert saved to database successfully.');
    } catch (saveError) {
      console.error('❌ Failed to save manual alert to database:', saveError);
    }
    
    res.status(200).json({
      status: 'success',
      message: 'Emergency alert sequence initiated and logged.',
      output: stdout
    });
  });
});
