/**
 * Alert Model
 * Handles notifications and alerts for the AgriUrbanAI platform
 */

const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  title: {
    type: String,
    required: [true, 'Alert title is required'],
    trim: true,
    maxlength: [100, 'Title cannot be more than 100 characters']
  },
  message: {
    type: String,
    required: [true, 'Alert message is required'],
    maxlength: [500, 'Message cannot be more than 500 characters']
  },
  type: {
    type: String,
    required: true,
    enum: [
      'weather', 'crop', 'flood', 'drought', 'pest', 'disease',
      'urban', 'traffic', 'emergency', 'maintenance', 'system',
      'agricultural', 'environmental', 'safety', 'info'
    ]
  },
  category: {
    type: String,
    enum: ['farmer', 'urban', 'admin', 'public', 'emergency'],
    default: 'farmer'
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical', 'emergency'],
    default: 'medium'
  },
  severity: {
    type: String,
    enum: ['info', 'warning', 'error', 'critical'],
    default: 'warning'
  },
  status: {
    type: String,
    enum: ['active', 'inactive', 'resolved', 'expired', 'cancelled'],
    default: 'active'
  },
  target: {
    users: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    }],
    roles: [{
      type: String,
      enum: ['farmer', 'urban', 'admin', 'demo']
    }],
    locations: [{
      district: String,
      state: String,
      coordinates: {
        type: {
          type: String,
          enum: ['Point'],
          default: 'Point'
        },
        coordinates: [Number] // [longitude, latitude]
      },
      radius: {
        type: Number, // in kilometers
        default: 50
      }
    }],
    crops: [String],
    departments: [String]
  },
  trigger: {
    conditions: {
      weather: {
        temperature: {
          min: Number,
          max: Number,
          operator: {
            type: String,
            enum: ['gt', 'gte', 'lt', 'lte', 'eq']
          }
        },
        humidity: {
          min: Number,
          max: Number,
          operator: {
            type: String,
            enum: ['gt', 'gte', 'lt', 'lte', 'eq']
          }
        },
        precipitation: {
          probability: {
            min: Number,
            operator: {
              type: String,
              enum: ['gt', 'gte', 'lt', 'lte', 'eq']
            }
          },
          amount: {
            min: Number,
            operator: {
              type: String,
              enum: ['gt', 'gte', 'lt', 'lte', 'eq']
            }
          }
        },
        windSpeed: {
          min: Number,
          operator: {
            type: String,
            enum: ['gt', 'gte', 'lt', 'lte', 'eq']
          }
        }
      },
      time: {
        startDate: Date,
        endDate: Date,
        recurring: {
          type: String,
          enum: ['daily', 'weekly', 'monthly', 'yearly']
        },
        timeOfDay: String // HH:MM format
      },
      crop: {
        stage: [String],
        health: {
          type: String,
          enum: ['excellent', 'good', 'fair', 'poor', 'critical']
        }
      }
    },
    source: {
      type: String,
      enum: ['manual', 'automated', 'weather-api', 'sensor', 'user-report'],
      default: 'manual'
    },
    autoGenerated: {
      type: Boolean,
      default: false
    }
  },
  schedule: {
    startTime: {
      type: Date,
      required: true,
      default: Date.now
    },
    endTime: Date,
    duration: Number, // in minutes
    recurring: {
      enabled: {
        type: Boolean,
        default: false
      },
      pattern: {
        type: String,
        enum: ['daily', 'weekly', 'monthly', 'yearly']
      },
      interval: {
        type: Number,
        default: 1
      },
      endDate: Date
    }
  },
  delivery: {
    channels: [{
      type: {
        type: String,
        enum: ['email', 'sms', 'push', 'voice', 'dashboard', 'system']
      },
      enabled: {
        type: Boolean,
        default: true
      },
      template: String,
      language: {
        type: String,
        enum: ['en', 'hi', 'mr', 'gu', 'ta', 'te', 'kn'],
        default: 'en'
      }
    }],
    sentCount: {
      type: Number,
      default: 0
    },
    deliveredCount: {
      type: Number,
      default: 0
    },
    readCount: {
      type: Number,
      default: 0
    },
    failedCount: {
      type: Number,
      default: 0
    }
  },
  actions: [{
    label: String,
    type: {
      type: String,
      enum: ['link', 'button', 'dismiss', 'acknowledge', 'custom']
    },
    url: String,
    action: String,
    primary: {
      type: Boolean,
      default: false
    }
  }],
  metadata: {
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    source: String,
    tags: [String],
    reference: String,
    externalId: String,
    expiresAt: Date,
    autoResolve: {
      enabled: {
        type: Boolean,
        default: false
      },
      conditions: String,
      timeout: Number // in minutes
    }
  },
  analytics: {
    views: {
      type: Number,
      default: 0
    },
    clicks: {
      type: Number,
      default: 0
    },
    conversions: {
      type: Number,
      default: 0
    },
    engagement: {
      type: Number,
      default: 0
    },
    feedback: [{
      user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
      },
      rating: {
        type: Number,
        min: 1,
        max: 5
      },
      comment: String,
      timestamp: {
        type: Date,
        default: Date.now
      }
    }]
  },
  responses: [{
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    action: String,
    timestamp: {
      type: Date,
      default: Date.now
    },
    data: mongoose.Schema.Types.Mixed
  }]
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes for performance
alertSchema.index({ type: 1 });
alertSchema.index({ priority: 1 });
alertSchema.index({ status: 1 });
alertSchema.index({ 'schedule.startTime': 1 });
alertSchema.index({ 'schedule.endTime': 1 });
alertSchema.index({ 'target.users': 1 });
alertSchema.index({ 'target.locations': '2dsphere' });
alertSchema.index({ createdAt: -1 });

// Virtual for active status
alertSchema.virtual('isActive').get(function() {
  const now = new Date();
  return this.status === 'active' &&
         this.schedule.startTime <= now &&
         (!this.schedule.endTime || this.schedule.endTime >= now);
});

// Virtual for expiry status
alertSchema.virtual('isExpired').get(function() {
  if (!this.metadata.expiresAt) return false;
  return new Date() > this.metadata.expiresAt;
});

// Virtual for delivery rate
alertSchema.virtual('deliveryRate').get(function() {
  if (this.delivery.sentCount === 0) return 0;
  return (this.delivery.deliveredCount / this.delivery.sentCount) * 100;
});

// Instance methods
alertSchema.methods = {
  // Check if alert targets a specific user
  targetsUser: function(user) {
    // Check if user is in target users
    if (this.target.users && this.target.users.includes(user._id)) {
      return true;
    }

    // Check if user's role is targeted
    if (this.target.roles && this.target.roles.includes(user.role)) {
      return true;
    }

    // Check if user's location is in target area
    if (this.target.locations && user.farm && user.farm.location) {
      return this.target.locations.some(location => {
        const distance = this.calculateDistance(
          location.coordinates.coordinates,
          user.farm.location.coordinates
        );
        return distance <= (location.radius || 50);
      });
    }

    // Check if user's crops are targeted
    if (this.target.crops && user.farm && user.farm.cropType) {
      return this.target.crops.some(crop =>
        user.farm.cropType.includes(crop)
      );
    }

    return false;
  },

  // Calculate distance between two points
  calculateDistance: function(point1, point2) {
    const [lon1, lat1] = point1;
    const [lon2, lat2] = point2;

    const R = 6371; // Earth's radius in km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a =
      Math.sin(dLat/2) * Math.sin(dLat/2) +
      Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
      Math.sin(dLon/2) * Math.sin(dLon/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
  },

  // Mark alert as read by user
  markAsRead: function(userId) {
    this.analytics.views += 1;
    return this.save();
  },

  // Record user response
  recordResponse: function(userId, action, data = {}) {
    this.responses.push({
      user: userId,
      action: action,
      data: data
    });

    if (action === 'click') {
      this.analytics.clicks += 1;
    }

    return this.save();
  },

  // Check if alert should auto-resolve
  shouldAutoResolve: function() {
    if (!this.metadata.autoResolve.enabled) return false;

    const now = new Date();
    const startTime = this.schedule.startTime;

    if (this.metadata.autoResolve.timeout) {
      const timeoutMs = this.metadata.autoResolve.timeout * 60 * 1000;
      return (now - startTime) >= timeoutMs;
    }

    return false;
  },

  // Get localized message
  getLocalizedMessage: function(language = 'en') {
    // This would integrate with a translation service
    // For now, return the original message
    return this.message;
  }
};

// Static methods
alertSchema.statics = {
  // Find active alerts for a user
  findActiveForUser: function(user) {
    return this.find({
      status: 'active',
      'schedule.startTime': { $lte: new Date() },
      $or: [
        { 'target.users': user._id },
        { 'target.roles': user.role },
        {
          'target.locations': {
            $elemMatch: {
              coordinates: {
                $near: {
                  $geometry: user.farm?.location || user.urbanProfile?.location,
                  $maxDistance: 50000 // 50km
                }
              }
            }
          }
        }
      ]
    }).sort({ priority: -1, createdAt: -1 });
  },

  // Find alerts by type and location
  findByTypeAndLocation: function(type, latitude, longitude, radius = 50) {
    return this.find({
      type: type,
      status: 'active',
      'target.locations': {
        $elemMatch: {
          coordinates: {
            $near: {
              $geometry: {
                type: 'Point',
                coordinates: [longitude, latitude]
              },
              $maxDistance: radius * 1000
            }
          }
        }
      }
    });
  },

  // Get alert statistics
  getStats: async function() {
    const stats = await this.aggregate([
      {
        $group: {
          _id: {
            type: '$type',
            priority: '$priority',
            status: '$status'
          },
          count: { $sum: 1 }
        }
      }
    ]);

    const totalAlerts = await this.countDocuments();
    const activeAlerts = await this.countDocuments({ status: 'active' });
    const emergencyAlerts = await this.countDocuments({
      priority: { $in: ['critical', 'emergency'] }
    });

    return {
      total: totalAlerts,
      active: activeAlerts,
      emergency: emergencyAlerts,
      byType: stats.reduce((acc, stat) => {
        if (!acc[stat._id.type]) acc[stat._id.type] = {};
        acc[stat._id.type][stat._id.priority] = stat.count;
        return acc;
      }, {}),
      byStatus: stats.reduce((acc, stat) => {
        if (!acc[stat._id.status]) acc[stat._id.status] = {};
        acc[stat._id.status][stat._id.priority] = stat.count;
        return acc;
      }, {})
    };
  },

  // Clean expired alerts
  cleanExpired: async function() {
    const now = new Date();
    const result = await this.updateMany(
      {
        $or: [
          { 'metadata.expiresAt': { $lt: now } },
          { 'schedule.endTime': { $lt: now } }
        ]
      },
      { status: 'expired' }
    );

    return result.modifiedCount;
  },

  // Create weather-based alert
  createWeatherAlert: function(weatherData, type, severity = 'medium') {
    const alertTypes = {
      'heavy-rain': 'Heavy rainfall expected',
      'drought': 'Drought conditions detected',
      'flood': 'Flood warning issued',
      'storm': 'Severe storm approaching',
      'heat': 'Heat wave conditions',
      'cold': 'Cold wave conditions'
    };

    return {
      title: alertTypes[type] || 'Weather Alert',
      message: `Weather alert for ${weatherData.location.name}. ${weatherData.current?.description || 'Check weather details.'}`,
      type: 'weather',
      priority: severity,
      target: {
        locations: [{
          district: weatherData.location.district,
          state: weatherData.location.state,
          coordinates: weatherData.location.coordinates,
          radius: 100
        }]
      },
      trigger: {
        source: 'automated',
        autoGenerated: true
      }
    };
  }
};

// Pre-save middleware
alertSchema.pre('save', function(next) {
  // Set expiry if not set and duration is specified
  if (!this.metadata.expiresAt && this.schedule.duration) {
    this.metadata.expiresAt = new Date(
      this.schedule.startTime.getTime() + (this.schedule.duration * 60 * 1000)
    );
  }

  // Auto-resolve if conditions are met
  if (this.shouldAutoResolve()) {
    this.status = 'resolved';
  }

  next();
});

// Post-save middleware
alertSchema.post('save', function(doc) {
  // Emit socket event for real-time updates
  if (doc.status === 'active') {
    // This would emit to connected clients
    // global.io?.emit('new-alert', doc);
  }
});

module.exports = mongoose.model('Alert', alertSchema);
